# Generated by Django 4.2.2 on 2023-07-17 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.IntegerField()),
                ('cedula', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='nombre_Propietario',
        ),
        migrations.AddField(
            model_name='departamento',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='departamento.propietario'),
            preserve_default=False,
        ),
    ]
