# Generated by Django 4.2.2 on 2023-07-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_propietario_remove_departamento_nombre_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
    ]
